### PR TITLE
Address book fix

### PR DESCRIPTION
**Pull request by carlosvdr**

### CODE REVIEW

**Review by aasseman — CHANGES_REQUESTED** [review]
https://github.com/semiotic-ai/timeline-aggregation-protocol-contracts/blob/5e7143d778795903b655c88d9d380dffbee28aac/bindings/bindings.ts#L41-L46
Is very hard to read. I'd prefer a basic `if ... else if ... else error` pattern.

Also:
- Missing signoffs on both commits
- (less important but weird) @ricardo-rp's commit signature is wrong. We can check that out-of-band later though.

**Review by aasseman — CHANGES_REQUESTED** [review]
No, I meant the whole block, like this:
```ts
  const deployedContracts = (
    addressBook ?
      addressBook[stringifiedChainId] :
      stringifiedChainId in DEPLOYED_CONTRACTS ?
        DEPLOYED_CONTRACTS[stringifiedChainId as keyof typeof DEPLOYED_CONTRACTS] :
        (() => { throw new Error(`chainId: '${chainId}' has no deployed contracts`); })()
  );
```
Not sure how to make it look nice (nor am I 100% it's correct TS code), but the logic is much simpler, and things get checked only once, no negations and such.

**Comment by ricardo-rp** [comment]
@aasseman @carlosvdr Take a look now. I think it's much more readable

**Comment by aasseman** [comment]
> @aasseman @carlosvdr Take a look now. I think it's much more readable

Yes, that's exactly what I had in mind, but didn't know how to do it in TS!

**Review by aasseman — APPROVED** [review]

**Pull request merged**
