### PR TITLE
Add bindings.ts file with network checks

### PR DESCRIPTION
**Pull request by carlosvdr**

### CODE REVIEW

**Review by aasseman — APPROVED** [review]
LGTM

**Comment by hopeyen** [comment]
At the moment `tap-contracts` does not provide type declarations within the git repo and no corresponding `@types/tap-contracts` packages, so the types can't be inferred when it get imported in indexer. 

I think it would be nice to declare the module in a `.d.ts` file and include in the project. You can indicate the types file with a line in package.json like `"types": "[...]/index.d.ts",`

**Comment by ricardo-rp** [comment]
> At the moment `tap-contracts` does not provide type declarations within the git repo and no corresponding `@types/tap-contracts` packages, so the types can't be inferred when it get imported in indexer.
> 
> I think it would be nice to declare the module in a `.d.ts` file and include in the project. You can indicate the types file with a line in package.json like `"types": "[...]/index.d.ts",`

The factories and type definitions are not in the source code. They need to be generated with the `bindings` command. I omitted them from source as I was thinking of putting this on npm, so they would be generated in CI.
@hopeyen If it'll be easier to use, we can commit the generated code and we can skip publishing to npm.

**Comment by carlosvdr** [comment]
@hopeyen yeah at the moment we will add the command to generate them into the readMe.
However we do plan on adding into npm to make it even easier.

**Comment by aasseman** [comment]
Won't that be fixed in the NPM release?

**Review by hopeyen — APPROVED** [review]
generated bindings worked 👍

**Review by ColePBryan — APPROVED** [review]

**Pull request merged**
